# Generated by Django 5.0.3 on 2024-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_links_add_7_new_B-Tree_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object2', 'object1', 'link_type'], name='links_obj2_obj1_lt_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object1', 'object2', 'link_type'], name='links_obj1_obj2_lt_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['object2', 'link_type', 'object1'], name='links_obj2_lt_obj1_idx'),
        ),
    ]
