# Generated by Django 4.2 on 2024-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0005_alter_chats_name_alter_chats_object_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="Chat",
            index=models.Index(fields=["created_date"], name="chats_cr_date_idx"),
        ),
        migrations.AddIndex(
            model_name="Chat",
            index=models.Index(fields=["modified_date"], name="chats_mod_date_idx"),
        ),
        migrations.AddIndex(
            model_name="Chat",
            index=models.Index(fields=["object_item", "object_type"], name="chats_o_item_type_idx"),
        ),
        migrations.AddIndex(
            model_name="Chat",
            index=models.Index(fields=["project_id", "account_id", "user_id"], name="chats_p_a_u_ids_idx"),
        ),
        migrations.AddIndex(
            model_name="Chat",
            index=models.Index(fields=["account_id", "user_id"], name="chats_a_u_ids_idx"),
        ),
        migrations.AddIndex(
            model_name="Chat",
            index=models.Index(fields=["user_id"], name="chats_user_id_idx"),
        ),
    ]
